server:
  port: 8080
  username-admin: ${USERNAME-ADMIN}
  password-admin: ${PASSWORD-ADMIN}

spring:
  datasource:
    url: "jdbc:postgresql://${HOST}:${PORT:5433}/${DATABASE}"
    username: ${USERNAME-DB:project1}
    password: ${PASSWORD-DB:pass_project1}
    driver-class-name: "org.postgresql.Driver"
  application:
    name: cookshare

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${USERNAME-MAIL}
    password: ${PASSWORD-MAIL}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  security:
    oauth2:
      registration:
        google:
          client-id: ${GG-CLIENT-ID}
          client-secret: ${GG-CLIENT-SECRET}
          redirect-uri: ${GOOGLE_REDIRECT_URI}
          user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
          resource-server:
            opaque-token:
                introspection-uri: "https://www.googleapis.com"
        facebook:
          client-id: ${FB-CLIENT-ID}
          client-secret: ${FB-CLIENT-SECRET}
          redirect-uri: ${FACEBOOK_REDIRECT_URI}
          auth-uri: https://www.facebook.com/v21.0/dialog/oauth
          token-uri: https://graph.facebook.com/v21.0/oauth/access_token
          user-info-uri: https://graph.facebook.com/me?fields=id,name,email,picture.type(large)
          scope: email,public_profile

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

cookshare:
  jwt:
    base64-secret: ${JWT-SECRET}
    access-token-validity-in-seconds: 86400
    refresh-token-validity-in-seconds: 8640000
    # WebSocket Configuration
    websocket:
      allowed-origins: ${WEBSOCKET_ORIGINS:http://localhost:3000,http://localhost:5173, http://localhost:4200}
      message-size-limit: 524288  # 512KB
      send-buffer-size-limit: 524288  # 512KB
      send-time-limit: 20000  # 20 seconds

firebase:
  storage:
    bucket: ${FIREBASE_STORAGE_BUCKET}
  credentials:
    path: ${FIREBASE_CREDENTIALS_PATH}

# Logging Configuration
logging:
  level:
    root: INFO
    com.backend.cookshare: DEBUG
  file:
    name: /app/logs/cookshare.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30
      total-size-cap: 1GB