server:
  port: 8080
  username-admin: admin
  password-admin: admin

spring:
  datasource:
    url: "jdbc:postgresql://localhost:5433/cookshare_db"
    username: project1
    password: pass_project1
    driver-class-name: "org.postgresql.Driver"
  application:
    name: cookshare

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: nhatplbn2004@gmail.com
    password: uelhjrmvojruvmiv
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  security:
    oauth2:
      registration:
        google:
          client-id: 930367083527-chtbv453jhlmdllanvtrf18sfigeqsvj.apps.googleusercontent.com
          client-secret: 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
          redirect-uri: "${GOOGLE_REDIRECT_URI:http://localhost:8080/auth/google/callback}"
          user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
          resource-server:
            opaque-token:
                introspection-uri: "https://www.googleapis.com"
        facebook:
          client-id: 1213805893870945
          client-secret: e13f0d954f2dd935931198e1486fa047
          redirect-uri: "${FACEBOOK_REDIRECT_URI:http://localhost:8080/auth/facebook/callback}"
          auth-uri: https://www.facebook.com/v21.0/dialog/oauth
          token-uri: https://graph.facebook.com/v21.0/oauth/access_token
          user-info-uri: https://graph.facebook.com/me?fields=id,name,email,picture.type(large)
          scope: email,public_profile

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

cookshare:
  jwt:
    base64-secret: qoAEABDke07+AVLepXB4aCMtsT0wMAqR5x2VFyldsnx6e75YQkJH2UcZKTjEyoNgG71SBCXfq5N6NVZxWOfsHQ==
    access-token-validity-in-seconds: 86400
    refresh-token-validity-in-seconds: 8640000
    # WebSocket Configuration
    websocket:
      allowed-origins:
        - http://localhost:3000
        - http://localhost:4200
        - http://localhost:5173
      message-size-limit: 524288  # 512KB
      send-buffer-size-limit: 524288  # 512KB
      send-time-limit: 20000  # 20 seconds